theme: jekyll-theme-minimal
title: Dr. Hetényi SE
author: $copy;GES
#avatar: "/assets/img/avatar-icon.png"
social-network-links:
  email: "drhetenyise@gmail.com"
  github: drhetenyise
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
#markdown: kramdown
github:
  is_project_page: false
#footer:
#  copyright_text: "&#127279; GES"
